# -*- coding: utf-8 -*-
"""Agricultural emissions reduction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSROzD0wJacIDiDMM95JgwQMI_ItgrJ7
"""

import pandas as pd

file_to_read = '/content/agriculture_emissions_dataset .csv'

try:
    # Attempt to read as CSV with default encoding
    df = pd.read_csv(file_to_read)
    print(f"Successfully read '{file_to_read}' as CSV.")
except UnicodeDecodeError:
    print(f"UnicodeDecodeError encountered while reading '{file_to_read}'. Trying 'latin1' encoding...")
    try:
        # Attempt to read as CSV with latin1 encoding
        df = pd.read_csv(file_to_read, encoding='latin1')
        print(f"Successfully read '{file_to_read}' with 'latin1' encoding.")
    except Exception as e:
        print(f"Failed to read '{file_to_read}' as CSV with 'latin1' encoding. Error: {e}")
        print(f"Attempting to read '{file_to_read}' as an Excel file...")
        try:
            # Fallback to reading as Excel
            df = pd.read_excel(file_to_read)
            print(f"Successfully read '{file_to_read}' as Excel.")
        except Exception as excel_e:
            print(f"Failed to read '{file_to_read}' as Excel. Error: {excel_e}")
            print("Please ensure the file is a valid CSV or Excel format and has the correct extension.")
            df = None # Indicate failure to load
except Exception as e:
    print(f"Failed to read '{file_to_read}' as CSV. Error: {e}")
    print(f"Attempting to read '{file_to_read}' as an Excel file...")
    try:
        # Fallback to reading as Excel
        df = pd.read_excel(file_to_read)
        print(f"Successfully read '{file_to_read}' as Excel.")
    except Exception as excel_e:
        print(f"Failed to read '{file_to_read}' as Excel. Error: {excel_e}")
        print("Please ensure the file is a valid CSV or Excel format and has the correct extension.")
        df = None # Indicate failure to load

if df is not None:
    print("\nFirst 5 rows of the dataset:")
    print(df.head())
    print("\nDataset Info:")
    df.info()

import numpy as np
import pandas as pd # Ensure pandas is imported, though it was in the first cell
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# --- Data Cleaning Function ---
def clean_numeric_column(df_target, column_name):
    """
    Cleans a column by removing non-numeric characters and converting it to float.
    Handles various formats like '£', '/unit', commas.
    """
    if column_name in df_target.columns and df_target[column_name].dtype == 'object':
        # Make a copy to avoid SettingWithCopyWarning
        # Remove currency symbols, commas, and common unit indicators to isolate numbers
        cleaned_series = df_target[column_name].astype(str).str.replace(r'[£,]', '', regex=True)
        # Extract numbers, including decimals. Added [0] to get the series from the DataFrame extract
        numeric_part = cleaned_series.str.extract(r'(-?\d+\.?\d*)')[0]
        # Convert to float, coercing errors to NaN
        df_target[column_name] = pd.to_numeric(numeric_part, errors='coerce')
        # Fill NaN values with 0. Consider using mean/median for more robust imputation if 0 is not appropriate.
        df_target[column_name] = df_target[column_name].fillna(0)
    return df_target

# Apply cleaning to relevant columns in df
df_numeric_cols_to_clean = [
    'Annual Reduction (tCO2e/yr)',
    'Implementation Cost (£)',
    'Cost/Tonne (£/tCO2e)',
    'Cost Savings (£/yr)'
]

for col_name in df_numeric_cols_to_clean:
    df = clean_numeric_column(df, col_name)

# Select input features
input_columns = [
    'Category',
    'Phase',
    'Scenario', # Corrected from 'Scenario Type'
    'Implementation Cost (£)', # Corrected from 'Estimated Implementation Cost (£)'
    'Time', # Corrected from 'Time Required for Implementation'
    'Feasibility', # Corrected from 'Feasibility Level'
    'Delivery', # Corrected from 'Suggested Delivery Method'
    'Action' # Corrected from 'Short-Term or Long-Term Action'
]

# Select target/output columns
output_columns = [
    'Annual Reduction (tCO2e/yr)', # Corrected from 'Estimated Annual Emissions Reduction (tCO2e/year)'
    'Lifetime Reduction (tCO2e)',
    'Cost/Tonne (£/tCO2e)', # Corrected from 'Cost per Tonne of Carbon Reduced (£/tCO2e)'
    'Cost Savings (£/yr)', # Corrected from 'Estimated Cost Savings (£/year)'
    'Adoption (%)' # Corrected from 'Farmer Adoption Likelihood (%)'
]

# Convert categorical columns into numbers
label_encoders = {}

# Ensure all input_columns exist in df before proceeding
missing_input_cols = [col for col in input_columns if col not in df.columns]
if missing_input_cols:
    raise ValueError(f"Missing input columns in DataFrame: {missing_input_cols}")

# Ensure all output_columns exist in df before proceeding
missing_output_cols = [col for col in output_columns if col not in df.columns]
if missing_output_cols:
    raise ValueError(f"Missing output columns in DataFrame: {missing_output_cols}")


for col in input_columns:
    # Only apply LabelEncoder to object type columns. Numeric columns should remain numeric.
    if df[col].dtype == 'object':
        le = LabelEncoder()
        # Fit on unique values to avoid errors if some values are not present in new_data
        df[col] = le.fit_transform(df[col].astype(str))
        label_encoders[col] = le

# Train separate models for each output
models = {}

for target in output_columns:
    print(f'\nTraining model for: {target}')

    X = df[input_columns]
    y = df[target]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = RandomForestRegressor(
        n_estimators=100,
        random_state=42
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    print(f'MAE: {mae:.2f}')
    print(f'R2 Score: {r2:.2f}')

    models[target] = model

# Example new input data for prediction
# IMPORTANT: Values must be chosen from existing categories in df to avoid transform errors
new_data = pd.DataFrame({
    'Category': ['Livestock'],
    'Phase': ['Phase 1'],
    'Scenario': ['High'], # Corrected from 'Scenario Type', and value chosen from df.Scenario.unique()
    'Implementation Cost (£)': [50000.0], # Corrected from 'Estimated Implementation Cost (£)', now numeric
    'Time': ['Long'], # Corrected from 'Time Required for Implementation', value chosen from df.Time.unique()
    'Feasibility': ['Medium'], # Corrected from 'Feasibility Level', value chosen from df.Feasibility.unique()
    'Delivery': ['Subsidy'], # Corrected from 'Suggested Delivery Method', value chosen from df.Delivery.unique()
    'Action': ['Long'] # Corrected from 'Short-Term or Long-Term Action', value chosen from df.Action.unique()
})

# Apply same label encoding to new_data
for col in new_data.columns:
    if col in label_encoders: # Only apply to columns that were label encoded in df
        # Check if the value in new_data exists in the fitted label encoder
        # If not, label_encoders[col].transform() would raise an error
        if new_data[col].iloc[0] not in label_encoders[col].classes_:
            print(f"Warning: Category '{new_data[col].iloc[0]}' for column '{col}' not seen during training. Using the first class as a fallback.")
            # Fallback to the first class label encountered during fitting
            new_data[col] = label_encoders[col].transform([label_encoders[col].classes_[0]])
        else:
            new_data[col] = label_encoders[col].transform(new_data[col].astype(str))
    elif col in df_numeric_cols_to_clean: # Ensure numeric columns in new_data are floats
        new_data[col] = new_data[col].astype(float)


# Predict outputs
print('\nPredicted Results:')

for target, model in models.items():
    prediction = model.predict(new_data)
    print(f'{target}: {prediction[0]:.2f}')